Pullup ticket #5823 - requested by bsiegert x11/libX11: security update
Revisions pulled up:
- x11/libX11/Makefile                                           1.46
- x11/libX11/PLIST                                              1.14
- x11/libX11/distinfo                                           1.28

-------------------------------------------------------------------
   Module Name:    pkgsrc
   Committed By:   wiz
   Date:           Tue Aug 21 19:29:48 UTC 2018

   Modified Files:
           pkgsrc/x11/libX11: Makefile PLIST distinfo

   Log Message:
   libX11: update to 1.6.6.

   Security fix release.

   Alan Coopersmith (6):
         Make Xkb{Get,Set}NamedIndicator spec & manpages match code
         Clarify state parameter to XkbSetNamedDeviceIndicator
         Improve table formatting in XkbChangeControls & XkbKeyNumGroups man pages
         If XGetImage fails to create image, don't dereference it to bounds check
         Use size_t for buffer sizes in SetHints.c
         Change fall through comment in lcDB.c to match gcc's requirements

   Arthur Huillet (1):
         _XDefaultError: set XlibDisplayIOError flag before calling exit

   Bhavi Dhingra (1):
         Fix possible memory leak in cmsProp.c:140

   Martin Natano (1):
         Don't rebuild ks_tables.h if nothing changed.

   Matthieu Herrb (2):
         Remove statement with no effect.
         libX11 1.6.6

   Michal Srb (1):
         Use flexible array member instead of fake size.

   Ryan C. Gordon (1):
         Valgrind fix for XStoreColor and XStoreColors.

   Samuel Thibault (1):
         XkbOpenDisplay.3: fix typo

   Tobias Stoeckmann (4):
         Validation of server response in XListHosts.
         Fixed off-by-one writes (CVE-2018-14599).
         Fixed out of boundary write (CVE-2018-14600).
         Fixed crash on invalid reply (CVE-2018-14598).

   walter harms (13):
         fix shadow warning
         _XIOError(dpy); will never return so remore dead
         remove argument check for free() adjust one inden
         fix shadow char_size
         fix more shadow warning
         no need to check argument for _XkbFree()
         remove stray extern
         no need to check args for Xfree()
         fix memleak in error path
         fix memleak in error path
         no need to check XFree arguments
         mark _XDefaultIOError as no_return
         Fixes: warning: variable 'req' set but not,used

   wharms (3):
         add _X_UNUSED to avoid unused variable warnings
         remove empty line
         silence gcc warning assignment discards 'const' qualifier from
   pointer target type


   To generate a diff of this commit:
   cvs rdiff -u -r1.45 -r1.46 pkgsrc/x11/libX11/Makefile
   cvs rdiff -u -r1.13 -r1.14 pkgsrc/x11/libX11/PLIST
   cvs rdiff -u -r1.27 -r1.28 pkgsrc/x11/libX11/distinfo